// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachment.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const attachToMessage = `-- name: AttachToMessage :exec
UPDATE message_attachments
SET message_id = $1
WHERE id = ANY($2::uuid[])
  AND uploader_id = $3
  AND conversation_id = $4
  AND message_id IS NULL
`

type AttachToMessageParams struct {
	MessageID      pgtype.UUID `db:"message_id" json:"messageId"`
	AttachmentIds  []uuid.UUID `db:"attachment_ids" json:"attachmentIds"`
	UploaderID     uuid.UUID   `db:"uploader_id" json:"uploaderId"`
	ConversationID uuid.UUID   `db:"conversation_id" json:"conversationId"`
}

func (q *Queries) AttachToMessage(ctx context.Context, arg AttachToMessageParams) error {
	_, err := q.db.Exec(ctx, attachToMessage,
		arg.MessageID,
		arg.AttachmentIds,
		arg.UploaderID,
		arg.ConversationID,
	)
	return err
}

const countPendingAttachments = `-- name: CountPendingAttachments :one
SELECT COUNT(*)::bigint
FROM message_attachments
WHERE id = ANY($1::uuid[])
  AND uploader_id = $2
  AND conversation_id = $3
  AND message_id IS NULL
`

type CountPendingAttachmentsParams struct {
	AttachmentIds  []uuid.UUID `db:"attachment_ids" json:"attachmentIds"`
	UploaderID     uuid.UUID   `db:"uploader_id" json:"uploaderId"`
	ConversationID uuid.UUID   `db:"conversation_id" json:"conversationId"`
}

func (q *Queries) CountPendingAttachments(ctx context.Context, arg CountPendingAttachmentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingAttachments, arg.AttachmentIds, arg.UploaderID, arg.ConversationID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO message_attachments (
    id, message_id, conversation_id, uploader_id,
    object_key, thumb_key, mime, kind, size_bytes,
    width, height, duration_ms, original_name, created_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14
)
RETURNING id, message_id, conversation_id, uploader_id, object_key, thumb_key, mime, kind, size_bytes, width, height, duration_ms, original_name, created_at
`

type CreateAttachmentParams struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	MessageID      pgtype.UUID        `db:"message_id" json:"messageId"`
	ConversationID uuid.UUID          `db:"conversation_id" json:"conversationId"`
	UploaderID     uuid.UUID          `db:"uploader_id" json:"uploaderId"`
	ObjectKey      string             `db:"object_key" json:"objectKey"`
	ThumbKey       pgtype.Text        `db:"thumb_key" json:"thumbKey"`
	Mime           string             `db:"mime" json:"mime"`
	Kind           string             `db:"kind" json:"kind"`
	SizeBytes      int64              `db:"size_bytes" json:"sizeBytes"`
	Width          pgtype.Int4        `db:"width" json:"width"`
	Height         pgtype.Int4        `db:"height" json:"height"`
	DurationMs     pgtype.Int4        `db:"duration_ms" json:"durationMs"`
	OriginalName   string             `db:"original_name" json:"originalName"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (MessageAttachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.ID,
		arg.MessageID,
		arg.ConversationID,
		arg.UploaderID,
		arg.ObjectKey,
		arg.ThumbKey,
		arg.Mime,
		arg.Kind,
		arg.SizeBytes,
		arg.Width,
		arg.Height,
		arg.DurationMs,
		arg.OriginalName,
		arg.CreatedAt,
	)
	var i MessageAttachment
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.ConversationID,
		&i.UploaderID,
		&i.ObjectKey,
		&i.ThumbKey,
		&i.Mime,
		&i.Kind,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.OriginalName,
		&i.CreatedAt,
	)
	return i, err
}

const getAttachmentByID = `-- name: GetAttachmentByID :one
SELECT id, message_id, conversation_id, uploader_id, object_key, thumb_key, mime, kind, size_bytes, width, height, duration_ms, original_name, created_at FROM message_attachments WHERE id = $1
`

func (q *Queries) GetAttachmentByID(ctx context.Context, id uuid.UUID) (MessageAttachment, error) {
	row := q.db.QueryRow(ctx, getAttachmentByID, id)
	var i MessageAttachment
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.ConversationID,
		&i.UploaderID,
		&i.ObjectKey,
		&i.ThumbKey,
		&i.Mime,
		&i.Kind,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.OriginalName,
		&i.CreatedAt,
	)
	return i, err
}

const listAttachmentsByMessageIDs = `-- name: ListAttachmentsByMessageIDs :many
SELECT id, message_id, conversation_id, uploader_id, object_key, thumb_key, mime, kind, size_bytes, width, height, duration_ms, original_name, created_at FROM message_attachments
WHERE message_id = ANY($1::uuid[])
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListAttachmentsByMessageIDs(ctx context.Context, messageIds []uuid.UUID) ([]MessageAttachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByMessageIDs, messageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessageAttachment{}
	for rows.Next() {
		var i MessageAttachment
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.ConversationID,
			&i.UploaderID,
			&i.ObjectKey,
			&i.ThumbKey,
			&i.Mime,
			&i.Kind,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
			&i.DurationMs,
			&i.OriginalName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationMedia = `-- name: ListConversationMedia :many
SELECT id, message_id, conversation_id, uploader_id, object_key, thumb_key, mime, kind, size_bytes, width, height, duration_ms, original_name, created_at
FROM message_attachments
WHERE conversation_id = $1
  AND message_id IS NOT NULL
  AND (
    $2::text = ''
    OR kind = $2::text
  )
  AND (
    $3::timestamptz IS NULL
    OR (created_at, id) < ($3::timestamptz, $4::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListConversationMediaParams struct {
	ConversationID  uuid.UUID          `db:"conversation_id" json:"conversationId"`
	Kind            string             `db:"kind" json:"kind"`
	CursorCreatedAt pgtype.Timestamptz `db:"cursor_created_at" json:"cursorCreatedAt"`
	CursorID        uuid.UUID          `db:"cursor_id" json:"cursorId"`
	Limit           int32              `db:"limit_" json:"limit"`
}

func (q *Queries) ListConversationMedia(ctx context.Context, arg ListConversationMediaParams) ([]MessageAttachment, error) {
	rows, err := q.db.Query(ctx, listConversationMedia,
		arg.ConversationID,
		arg.Kind,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessageAttachment{}
	for rows.Next() {
		var i MessageAttachment
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.ConversationID,
			&i.UploaderID,
			&i.ObjectKey,
			&i.ThumbKey,
			&i.Mime,
			&i.Kind,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
			&i.DurationMs,
			&i.OriginalName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
