// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addConversationMember = `-- name: AddConversationMember :exec
INSERT INTO conversation_members (id, conversation_id, user_id, joined_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (conversation_id, user_id) DO NOTHING
`

type AddConversationMemberParams struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	ConversationID uuid.UUID          `db:"conversation_id" json:"conversationId"`
	UserID         uuid.UUID          `db:"user_id" json:"userId"`
	JoinedAt       pgtype.Timestamptz `db:"joined_at" json:"joinedAt"`
}

func (q *Queries) AddConversationMember(ctx context.Context, arg AddConversationMemberParams) error {
	_, err := q.db.Exec(ctx, addConversationMember,
		arg.ID,
		arg.ConversationID,
		arg.UserID,
		arg.JoinedAt,
	)
	return err
}

const conversationExists = `-- name: ConversationExists :one
SELECT EXISTS (SELECT 1
               FROM conversations
               WHERE id = $1)
`

func (q *Queries) ConversationExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, conversationExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (id, type, title, slug, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, type, title, slug, created_at
`

type CreateConversationParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Type      ConversationType   `db:"type" json:"type"`
	Title     pgtype.Text        `db:"title" json:"title"`
	Slug      pgtype.Text        `db:"slug" json:"slug"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation,
		arg.ID,
		arg.Type,
		arg.Title,
		arg.Slug,
		arg.CreatedAt,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const createDMPair = `-- name: CreateDMPair :exec
INSERT INTO dm_pairs (user_low, user_high, conversation_id)
VALUES ($1, $2, $3)
`

type CreateDMPairParams struct {
	UserLow        uuid.UUID `db:"user_low" json:"userLow"`
	UserHigh       uuid.UUID `db:"user_high" json:"userHigh"`
	ConversationID uuid.UUID `db:"conversation_id" json:"conversationId"`
}

func (q *Queries) CreateDMPair(ctx context.Context, arg CreateDMPairParams) error {
	_, err := q.db.Exec(ctx, createDMPair, arg.UserLow, arg.UserHigh, arg.ConversationID)
	return err
}

const findDMConversation = `-- name: FindDMConversation :one
SELECT conversation_id
FROM dm_pairs
WHERE user_low = $1
  AND user_high = $2
`

type FindDMConversationParams struct {
	UserLow  uuid.UUID `db:"user_low" json:"userLow"`
	UserHigh uuid.UUID `db:"user_high" json:"userHigh"`
}

func (q *Queries) FindDMConversation(ctx context.Context, arg FindDMConversationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findDMConversation, arg.UserLow, arg.UserHigh)
	var conversation_id uuid.UUID
	err := row.Scan(&conversation_id)
	return conversation_id, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, type, title, slug, created_at
FROM conversations
WHERE id = $1
`

func (q *Queries) GetConversation(ctx context.Context, id uuid.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getConversationBySlug = `-- name: GetConversationBySlug :one
SELECT id, type, title, slug, created_at
FROM conversations
WHERE slug = $1
LIMIT 1
`

func (q *Queries) GetConversationBySlug(ctx context.Context, slug pgtype.Text) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationBySlug, slug)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getUserConversations = `-- name: GetUserConversations :many
SELECT c.id, c.type, c.title, c.slug, c.created_at
FROM conversations c
         JOIN conversation_members cm ON cm.conversation_id = c.id
WHERE cm.user_id = $1
ORDER BY c.created_at DESC
`

func (q *Queries) GetUserConversations(ctx context.Context, userID uuid.UUID) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, getUserConversations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isConversationMember = `-- name: IsConversationMember :one
SELECT EXISTS (SELECT 1
               FROM conversation_members
               WHERE conversation_id = $1
                 AND user_id = $2)
`

type IsConversationMemberParams struct {
	ConversationID uuid.UUID `db:"conversation_id" json:"conversationId"`
	UserID         uuid.UUID `db:"user_id" json:"userId"`
}

func (q *Queries) IsConversationMember(ctx context.Context, arg IsConversationMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isConversationMember, arg.ConversationID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
