// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addConversationMember = `-- name: AddConversationMember :exec
INSERT INTO conversation_members (id, conversation_id, user_id, joined_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (conversation_id, user_id) DO NOTHING
`

type AddConversationMemberParams struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	ConversationID uuid.UUID          `db:"conversation_id" json:"conversationId"`
	UserID         uuid.UUID          `db:"user_id" json:"userId"`
	JoinedAt       pgtype.Timestamptz `db:"joined_at" json:"joinedAt"`
}

func (q *Queries) AddConversationMember(ctx context.Context, arg AddConversationMemberParams) error {
	_, err := q.db.Exec(ctx, addConversationMember,
		arg.ID,
		arg.ConversationID,
		arg.UserID,
		arg.JoinedAt,
	)
	return err
}

const conversationExists = `-- name: ConversationExists :one
SELECT EXISTS (SELECT 1
               FROM conversations
               WHERE id = $1)
`

func (q *Queries) ConversationExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, conversationExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (id, type, title, slug, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, type, title, slug, created_at
`

type CreateConversationParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Type      ConversationType   `db:"type" json:"type"`
	Title     pgtype.Text        `db:"title" json:"title"`
	Slug      pgtype.Text        `db:"slug" json:"slug"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation,
		arg.ID,
		arg.Type,
		arg.Title,
		arg.Slug,
		arg.CreatedAt,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const createDMPair = `-- name: CreateDMPair :exec
INSERT INTO dm_pairs (user_low, user_high, conversation_id)
VALUES ($1, $2, $3)
`

type CreateDMPairParams struct {
	UserLow        uuid.UUID `db:"user_low" json:"userLow"`
	UserHigh       uuid.UUID `db:"user_high" json:"userHigh"`
	ConversationID uuid.UUID `db:"conversation_id" json:"conversationId"`
}

func (q *Queries) CreateDMPair(ctx context.Context, arg CreateDMPairParams) error {
	_, err := q.db.Exec(ctx, createDMPair, arg.UserLow, arg.UserHigh, arg.ConversationID)
	return err
}

const findDMConversation = `-- name: FindDMConversation :one
SELECT conversation_id
FROM dm_pairs
WHERE user_low = $1
  AND user_high = $2
`

type FindDMConversationParams struct {
	UserLow  uuid.UUID `db:"user_low" json:"userLow"`
	UserHigh uuid.UUID `db:"user_high" json:"userHigh"`
}

func (q *Queries) FindDMConversation(ctx context.Context, arg FindDMConversationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findDMConversation, arg.UserLow, arg.UserHigh)
	var conversation_id uuid.UUID
	err := row.Scan(&conversation_id)
	return conversation_id, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, type, title, slug, created_at
FROM conversations
WHERE id = $1
`

func (q *Queries) GetConversation(ctx context.Context, id uuid.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getConversationBySlug = `-- name: GetConversationBySlug :one
SELECT id, type, title, slug, created_at
FROM conversations
WHERE slug = $1
LIMIT 1
`

func (q *Queries) GetConversationBySlug(ctx context.Context, slug pgtype.Text) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationBySlug, slug)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getUserConversations = `-- name: GetUserConversations :many
SELECT c.id,
       c.type,
       c.title,
       c.slug,
       c.created_at,
       peer.id            AS peer_id,
       peer.username      AS peer_username,
       peer.avatar_url    AS peer_avatar_url,
       lm.id              AS last_message_id,
       lm.content         AS last_message_content,
       lm.created_at      AS last_message_created_at,
       lm_sender.username AS last_message_sender_username,
       COALESCE(att.kind, '') AS last_message_attachment_kind
FROM conversations c
         JOIN conversation_members cm ON cm.conversation_id = c.id AND cm.user_id = $1
         LEFT JOIN conversation_members pcm
                   ON pcm.conversation_id = c.id AND pcm.user_id <> $1 AND c.type = 'dm'
         LEFT JOIN users peer ON peer.id = pcm.user_id
         LEFT JOIN messages lm ON lm.id = (
    SELECT m.id
    FROM messages m
    WHERE m.conversation_id = c.id
      AND m.deleted_at IS NULL
      AND NOT EXISTS (
        SELECT 1
        FROM hidden_messages hm
        WHERE hm.message_id = m.id
          AND hm.user_id = $1
    )
    ORDER BY m.created_at DESC, m.id DESC
    LIMIT 1
    )
         LEFT JOIN users lm_sender ON lm_sender.id = lm.sender_id
         LEFT JOIN LATERAL (
    SELECT a.kind
    FROM message_attachments a
    WHERE a.message_id = lm.id
    ORDER BY a.created_at ASC, a.id ASC
    LIMIT 1
    ) att ON TRUE
ORDER BY COALESCE(lm.created_at, c.created_at) DESC, c.id DESC
`

type GetUserConversationsRow struct {
	ID                        uuid.UUID          `db:"id" json:"id"`
	Type                      ConversationType   `db:"type" json:"type"`
	Title                     pgtype.Text        `db:"title" json:"title"`
	Slug                      pgtype.Text        `db:"slug" json:"slug"`
	CreatedAt                 pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	PeerID                    pgtype.UUID        `db:"peer_id" json:"peerId"`
	PeerUsername              pgtype.Text        `db:"peer_username" json:"peerUsername"`
	PeerAvatarUrl             pgtype.Text        `db:"peer_avatar_url" json:"peerAvatarUrl"`
	LastMessageID             pgtype.UUID        `db:"last_message_id" json:"lastMessageId"`
	LastMessageContent        pgtype.Text        `db:"last_message_content" json:"lastMessageContent"`
	LastMessageCreatedAt      pgtype.Timestamptz `db:"last_message_created_at" json:"lastMessageCreatedAt"`
	LastMessageSenderUsername pgtype.Text        `db:"last_message_sender_username" json:"lastMessageSenderUsername"`
	LastMessageAttachmentKind string             `db:"last_message_attachment_kind" json:"lastMessageAttachmentKind"`
}

func (q *Queries) GetUserConversations(ctx context.Context, userID uuid.UUID) ([]GetUserConversationsRow, error) {
	rows, err := q.db.Query(ctx, getUserConversations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserConversationsRow{}
	for rows.Next() {
		var i GetUserConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Slug,
			&i.CreatedAt,
			&i.PeerID,
			&i.PeerUsername,
			&i.PeerAvatarUrl,
			&i.LastMessageID,
			&i.LastMessageContent,
			&i.LastMessageCreatedAt,
			&i.LastMessageSenderUsername,
			&i.LastMessageAttachmentKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isConversationMember = `-- name: IsConversationMember :one
SELECT EXISTS (SELECT 1
               FROM conversation_members
               WHERE conversation_id = $1
                 AND user_id = $2)
`

type IsConversationMemberParams struct {
	ConversationID uuid.UUID `db:"conversation_id" json:"conversationId"`
	UserID         uuid.UUID `db:"user_id" json:"userId"`
}

func (q *Queries) IsConversationMember(ctx context.Context, arg IsConversationMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isConversationMember, arg.ConversationID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const removeConversationMember = `-- name: RemoveConversationMember :exec
DELETE
FROM conversation_members
WHERE conversation_id = $1
  AND user_id = $2
`

type RemoveConversationMemberParams struct {
	ConversationID uuid.UUID `db:"conversation_id" json:"conversationId"`
	UserID         uuid.UUID `db:"user_id" json:"userId"`
}

func (q *Queries) RemoveConversationMember(ctx context.Context, arg RemoveConversationMemberParams) error {
	_, err := q.db.Exec(ctx, removeConversationMember, arg.ConversationID, arg.UserID)
	return err
}
