// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: folder.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addChatFolderItem = `-- name: AddChatFolderItem :exec
INSERT INTO chat_folder_items (folder_id, conversation_id, added_at)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddChatFolderItemParams struct {
	FolderID       uuid.UUID          `db:"folder_id" json:"folderId"`
	ConversationID uuid.UUID          `db:"conversation_id" json:"conversationId"`
	AddedAt        pgtype.Timestamptz `db:"added_at" json:"addedAt"`
}

func (q *Queries) AddChatFolderItem(ctx context.Context, arg AddChatFolderItemParams) error {
	_, err := q.db.Exec(ctx, addChatFolderItem, arg.FolderID, arg.ConversationID, arg.AddedAt)
	return err
}

const chatFolderItemExists = `-- name: ChatFolderItemExists :one
SELECT EXISTS (
    SELECT 1
    FROM chat_folder_items
    WHERE folder_id = $1
      AND conversation_id = $2
)
`

type ChatFolderItemExistsParams struct {
	FolderID       uuid.UUID `db:"folder_id" json:"folderId"`
	ConversationID uuid.UUID `db:"conversation_id" json:"conversationId"`
}

func (q *Queries) ChatFolderItemExists(ctx context.Context, arg ChatFolderItemExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, chatFolderItemExists, arg.FolderID, arg.ConversationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countChatFolderItems = `-- name: CountChatFolderItems :one
SELECT COUNT(*)::int
FROM chat_folder_items
WHERE folder_id = $1
`

func (q *Queries) CountChatFolderItems(ctx context.Context, folderID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countChatFolderItems, folderID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countUserChatFolders = `-- name: CountUserChatFolders :one
SELECT COUNT(*)::int
FROM chat_folders
WHERE user_id = $1
`

func (q *Queries) CountUserChatFolders(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countUserChatFolders, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createChatFolder = `-- name: CreateChatFolder :one
INSERT INTO chat_folders (id, user_id, name, icon, position, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, name, icon, position, created_at, updated_at
`

type CreateChatFolderParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    uuid.UUID          `db:"user_id" json:"userId"`
	Name      string             `db:"name" json:"name"`
	Icon      pgtype.Text        `db:"icon" json:"icon"`
	Position  int32              `db:"position" json:"position"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

func (q *Queries) CreateChatFolder(ctx context.Context, arg CreateChatFolderParams) (ChatFolder, error) {
	row := q.db.QueryRow(ctx, createChatFolder,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Icon,
		arg.Position,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ChatFolder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Icon,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChatFolder = `-- name: DeleteChatFolder :exec
DELETE FROM chat_folders
WHERE id = $1
  AND user_id = $2
`

type DeleteChatFolderParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"userId"`
}

func (q *Queries) DeleteChatFolder(ctx context.Context, arg DeleteChatFolderParams) error {
	_, err := q.db.Exec(ctx, deleteChatFolder, arg.ID, arg.UserID)
	return err
}

const getChatFolder = `-- name: GetChatFolder :one
SELECT id, user_id, name, icon, position, created_at, updated_at
FROM chat_folders
WHERE id = $1
`

func (q *Queries) GetChatFolder(ctx context.Context, id uuid.UUID) (ChatFolder, error) {
	row := q.db.QueryRow(ctx, getChatFolder, id)
	var i ChatFolder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Icon,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFolderIDsByConversations = `-- name: GetFolderIDsByConversations :many
SELECT cfi.conversation_id, cfi.folder_id
FROM chat_folder_items cfi
         JOIN chat_folders cf ON cf.id = cfi.folder_id
WHERE cf.user_id = $1
`

type GetFolderIDsByConversationsRow struct {
	ConversationID uuid.UUID `db:"conversation_id" json:"conversationId"`
	FolderID       uuid.UUID `db:"folder_id" json:"folderId"`
}

func (q *Queries) GetFolderIDsByConversations(ctx context.Context, userID uuid.UUID) ([]GetFolderIDsByConversationsRow, error) {
	rows, err := q.db.Query(ctx, getFolderIDsByConversations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFolderIDsByConversationsRow{}
	for rows.Next() {
		var i GetFolderIDsByConversationsRow
		if err := rows.Scan(&i.ConversationID, &i.FolderID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFolderIDsForConversation = `-- name: GetFolderIDsForConversation :many
SELECT cfi.folder_id
FROM chat_folder_items cfi
         JOIN chat_folders cf ON cf.id = cfi.folder_id
WHERE cfi.conversation_id = $1
  AND cf.user_id = $2
`

type GetFolderIDsForConversationParams struct {
	ConversationID uuid.UUID `db:"conversation_id" json:"conversationId"`
	UserID         uuid.UUID `db:"user_id" json:"userId"`
}

func (q *Queries) GetFolderIDsForConversation(ctx context.Context, arg GetFolderIDsForConversationParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getFolderIDsForConversation, arg.ConversationID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var folder_id uuid.UUID
		if err := rows.Scan(&folder_id); err != nil {
			return nil, err
		}
		items = append(items, folder_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatFolders = `-- name: ListChatFolders :many
SELECT id, user_id, name, icon, position, created_at, updated_at
FROM chat_folders
WHERE user_id = $1
ORDER BY position, created_at
`

func (q *Queries) ListChatFolders(ctx context.Context, userID uuid.UUID) ([]ChatFolder, error) {
	rows, err := q.db.Query(ctx, listChatFolders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatFolder{}
	for rows.Next() {
		var i ChatFolder
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Icon,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxChatFolderPosition = `-- name: MaxChatFolderPosition :one
SELECT COALESCE(MAX(position), -1)::int
FROM chat_folders
WHERE user_id = $1
`

func (q *Queries) MaxChatFolderPosition(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, maxChatFolderPosition, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const removeChatFolderItem = `-- name: RemoveChatFolderItem :exec
DELETE FROM chat_folder_items
WHERE folder_id = $1
  AND conversation_id = $2
`

type RemoveChatFolderItemParams struct {
	FolderID       uuid.UUID `db:"folder_id" json:"folderId"`
	ConversationID uuid.UUID `db:"conversation_id" json:"conversationId"`
}

func (q *Queries) RemoveChatFolderItem(ctx context.Context, arg RemoveChatFolderItemParams) error {
	_, err := q.db.Exec(ctx, removeChatFolderItem, arg.FolderID, arg.ConversationID)
	return err
}

const updateChatFolder = `-- name: UpdateChatFolder :one
UPDATE chat_folders
SET name       = $2,
    icon       = $3,
    updated_at = $4
WHERE id = $1
  AND user_id = $5
RETURNING id, user_id, name, icon, position, created_at, updated_at
`

type UpdateChatFolderParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Icon      pgtype.Text        `db:"icon" json:"icon"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
	UserID    uuid.UUID          `db:"user_id" json:"userId"`
}

func (q *Queries) UpdateChatFolder(ctx context.Context, arg UpdateChatFolderParams) (ChatFolder, error) {
	row := q.db.QueryRow(ctx, updateChatFolder,
		arg.ID,
		arg.Name,
		arg.Icon,
		arg.UpdatedAt,
		arg.UserID,
	)
	var i ChatFolder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Icon,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateChatFolderPosition = `-- name: UpdateChatFolderPosition :exec
UPDATE chat_folders
SET position   = $2,
    updated_at = NOW()
WHERE id = $1
  AND user_id = $3
`

type UpdateChatFolderPositionParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	Position int32     `db:"position" json:"position"`
	UserID   uuid.UUID `db:"user_id" json:"userId"`
}

func (q *Queries) UpdateChatFolderPosition(ctx context.Context, arg UpdateChatFolderPositionParams) error {
	_, err := q.db.Exec(ctx, updateChatFolderPosition, arg.ID, arg.Position, arg.UserID)
	return err
}
