// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ConversationType string

const (
	ConversationTypeDm    ConversationType = "dm"
	ConversationTypeGroup ConversationType = "group"
)

func (e *ConversationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConversationType(s)
	case string:
		*e = ConversationType(s)
	default:
		return fmt.Errorf("unsupported scan type for ConversationType: %T", src)
	}
	return nil
}

type NullConversationType struct {
	ConversationType ConversationType `json:"conversationType"`
	Valid            bool             `json:"valid"` // Valid is true if ConversationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConversationType) Scan(value interface{}) error {
	if value == nil {
		ns.ConversationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConversationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConversationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConversationType), nil
}

type DecisionStatus string

const (
	DecisionStatusProposed   DecisionStatus = "proposed"
	DecisionStatusAccepted   DecisionStatus = "accepted"
	DecisionStatusDeprecated DecisionStatus = "deprecated"
)

func (e *DecisionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DecisionStatus(s)
	case string:
		*e = DecisionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DecisionStatus: %T", src)
	}
	return nil
}

type NullDecisionStatus struct {
	DecisionStatus DecisionStatus `json:"decisionStatus"`
	Valid          bool           `json:"valid"` // Valid is true if DecisionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDecisionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DecisionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DecisionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDecisionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DecisionStatus), nil
}

type ProjectMemberRole string

const (
	ProjectMemberRoleOwner  ProjectMemberRole = "owner"
	ProjectMemberRoleMember ProjectMemberRole = "member"
)

func (e *ProjectMemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProjectMemberRole(s)
	case string:
		*e = ProjectMemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for ProjectMemberRole: %T", src)
	}
	return nil
}

type NullProjectMemberRole struct {
	ProjectMemberRole ProjectMemberRole `json:"projectMemberRole"`
	Valid             bool              `json:"valid"` // Valid is true if ProjectMemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProjectMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.ProjectMemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProjectMemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProjectMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProjectMemberRole), nil
}

type Conversation struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Type      ConversationType   `db:"type" json:"type"`
	Title     pgtype.Text        `db:"title" json:"title"`
	Slug      pgtype.Text        `db:"slug" json:"slug"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

type ConversationMember struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	ConversationID uuid.UUID          `db:"conversation_id" json:"conversationId"`
	UserID         uuid.UUID          `db:"user_id" json:"userId"`
	JoinedAt       pgtype.Timestamptz `db:"joined_at" json:"joinedAt"`
	LastReadAt     pgtype.Timestamptz `db:"last_read_at" json:"lastReadAt"`
}

type DmPair struct {
	UserLow        uuid.UUID `db:"user_low" json:"userLow"`
	UserHigh       uuid.UUID `db:"user_high" json:"userHigh"`
	ConversationID uuid.UUID `db:"conversation_id" json:"conversationId"`
}

type HiddenMessage struct {
	MessageID uuid.UUID          `db:"message_id" json:"messageId"`
	UserID    uuid.UUID          `db:"user_id" json:"userId"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

type Message struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	ConversationID  uuid.UUID          `db:"conversation_id" json:"conversationId"`
	SenderID        uuid.UUID          `db:"sender_id" json:"senderId"`
	Content         string             `db:"content" json:"content"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	ReplyToID       pgtype.UUID        `db:"reply_to_id" json:"replyToId"`
	ForwardedFromID pgtype.UUID        `db:"forwarded_from_id" json:"forwardedFromId"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at" json:"deletedAt"`
}

type MessageAttachment struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	MessageID      pgtype.UUID        `db:"message_id" json:"messageId"`
	ConversationID uuid.UUID          `db:"conversation_id" json:"conversationId"`
	UploaderID     uuid.UUID          `db:"uploader_id" json:"uploaderId"`
	ObjectKey      string             `db:"object_key" json:"objectKey"`
	ThumbKey       pgtype.Text        `db:"thumb_key" json:"thumbKey"`
	Mime           string             `db:"mime" json:"mime"`
	Kind           string             `db:"kind" json:"kind"`
	SizeBytes      int64              `db:"size_bytes" json:"sizeBytes"`
	Width          pgtype.Int4        `db:"width" json:"width"`
	Height         pgtype.Int4        `db:"height" json:"height"`
	DurationMs     pgtype.Int4        `db:"duration_ms" json:"durationMs"`
	OriginalName   string             `db:"original_name" json:"originalName"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

type MessageReaction struct {
	MessageID uuid.UUID          `db:"message_id" json:"messageId"`
	UserID    uuid.UUID          `db:"user_id" json:"userId"`
	Emoji     string             `db:"emoji" json:"emoji"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

type PhoneOtpCode struct {
	Phone     string             `db:"phone" json:"phone"`
	CodeHash  string             `db:"code_hash" json:"codeHash"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expiresAt"`
	Attempts  int32              `db:"attempts" json:"attempts"`
	SentAt    pgtype.Timestamptz `db:"sent_at" json:"sentAt"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

type Project struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	Description string             `db:"description" json:"description"`
	CreatedBy   uuid.UUID          `db:"created_by" json:"createdBy"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

type ProjectConversation struct {
	ProjectID      uuid.UUID          `db:"project_id" json:"projectId"`
	ConversationID uuid.UUID          `db:"conversation_id" json:"conversationId"`
	LinkedAt       pgtype.Timestamptz `db:"linked_at" json:"linkedAt"`
}

type ProjectDecision struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	ProjectID uuid.UUID          `db:"project_id" json:"projectId"`
	Summary   string             `db:"summary" json:"summary"`
	Context   string             `db:"context" json:"context"`
	Status    DecisionStatus     `db:"status" json:"status"`
	MessageID pgtype.UUID        `db:"message_id" json:"messageId"`
	CreatedBy uuid.UUID          `db:"created_by" json:"createdBy"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

type ProjectDoc struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	ProjectID uuid.UUID          `db:"project_id" json:"projectId"`
	Slug      string             `db:"slug" json:"slug"`
	Title     string             `db:"title" json:"title"`
	BodyMd    string             `db:"body_md" json:"bodyMd"`
	CreatedBy uuid.UUID          `db:"created_by" json:"createdBy"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

type ProjectMember struct {
	ProjectID uuid.UUID          `db:"project_id" json:"projectId"`
	UserID    uuid.UUID          `db:"user_id" json:"userId"`
	Role      ProjectMemberRole  `db:"role" json:"role"`
	JoinedAt  pgtype.Timestamptz `db:"joined_at" json:"joinedAt"`
}

type User struct {
	ID                 uuid.UUID          `db:"id" json:"id"`
	Phone              string             `db:"phone" json:"phone"`
	Username           pgtype.Text        `db:"username" json:"username"`
	PasswordHash       pgtype.Text        `db:"password_hash" json:"passwordHash"`
	AvatarUrl          pgtype.Text        `db:"avatar_url" json:"avatarUrl"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UsernameSearchable bool               `db:"username_searchable" json:"usernameSearchable"`
	DmPolicy           string             `db:"dm_policy" json:"dmPolicy"`
}
