// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addProjectMember = `-- name: AddProjectMember :exec
INSERT INTO project_members (project_id, user_id, role, joined_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (project_id, user_id) DO NOTHING
`

type AddProjectMemberParams struct {
	ProjectID uuid.UUID          `db:"project_id" json:"projectId"`
	UserID    uuid.UUID          `db:"user_id" json:"userId"`
	Role      ProjectMemberRole  `db:"role" json:"role"`
	JoinedAt  pgtype.Timestamptz `db:"joined_at" json:"joinedAt"`
}

func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) error {
	_, err := q.db.Exec(ctx, addProjectMember,
		arg.ProjectID,
		arg.UserID,
		arg.Role,
		arg.JoinedAt,
	)
	return err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, name, description, created_by, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, created_by, created_at
`

type CreateProjectParams struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	Description string             `db:"description" json:"description"`
	CreatedBy   uuid.UUID          `db:"created_by" json:"createdBy"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createProjectDecision = `-- name: CreateProjectDecision :one
INSERT INTO project_decisions (id, project_id, summary, context, status, message_id, created_by, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, project_id, summary, context, status, message_id, created_by, created_at
`

type CreateProjectDecisionParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	ProjectID uuid.UUID          `db:"project_id" json:"projectId"`
	Summary   string             `db:"summary" json:"summary"`
	Context   string             `db:"context" json:"context"`
	Status    DecisionStatus     `db:"status" json:"status"`
	MessageID pgtype.UUID        `db:"message_id" json:"messageId"`
	CreatedBy uuid.UUID          `db:"created_by" json:"createdBy"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

func (q *Queries) CreateProjectDecision(ctx context.Context, arg CreateProjectDecisionParams) (ProjectDecision, error) {
	row := q.db.QueryRow(ctx, createProjectDecision,
		arg.ID,
		arg.ProjectID,
		arg.Summary,
		arg.Context,
		arg.Status,
		arg.MessageID,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	var i ProjectDecision
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Summary,
		&i.Context,
		&i.Status,
		&i.MessageID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createProjectDoc = `-- name: CreateProjectDoc :one
INSERT INTO project_docs (id, project_id, slug, title, body_md, created_by, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, slug, title, body_md, created_by, updated_at
`

type CreateProjectDocParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	ProjectID uuid.UUID          `db:"project_id" json:"projectId"`
	Slug      string             `db:"slug" json:"slug"`
	Title     string             `db:"title" json:"title"`
	BodyMd    string             `db:"body_md" json:"bodyMd"`
	CreatedBy uuid.UUID          `db:"created_by" json:"createdBy"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

func (q *Queries) CreateProjectDoc(ctx context.Context, arg CreateProjectDocParams) (ProjectDoc, error) {
	row := q.db.QueryRow(ctx, createProjectDoc,
		arg.ID,
		arg.ProjectID,
		arg.Slug,
		arg.Title,
		arg.BodyMd,
		arg.CreatedBy,
		arg.UpdatedAt,
	)
	var i ProjectDoc
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Title,
		&i.BodyMd,
		&i.CreatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProjectDoc = `-- name: DeleteProjectDoc :exec
DELETE
FROM project_docs
WHERE id = $1
  AND project_id = $2
`

type DeleteProjectDocParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	ProjectID uuid.UUID `db:"project_id" json:"projectId"`
}

func (q *Queries) DeleteProjectDoc(ctx context.Context, arg DeleteProjectDocParams) error {
	_, err := q.db.Exec(ctx, deleteProjectDoc, arg.ID, arg.ProjectID)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, name, description, created_by, created_at
FROM projects
WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectDecision = `-- name: GetProjectDecision :one
SELECT id, project_id, summary, context, status, message_id, created_by, created_at
FROM project_decisions
WHERE id = $1
  AND project_id = $2
`

type GetProjectDecisionParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	ProjectID uuid.UUID `db:"project_id" json:"projectId"`
}

func (q *Queries) GetProjectDecision(ctx context.Context, arg GetProjectDecisionParams) (ProjectDecision, error) {
	row := q.db.QueryRow(ctx, getProjectDecision, arg.ID, arg.ProjectID)
	var i ProjectDecision
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Summary,
		&i.Context,
		&i.Status,
		&i.MessageID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectDoc = `-- name: GetProjectDoc :one
SELECT id, project_id, slug, title, body_md, created_by, updated_at
FROM project_docs
WHERE id = $1
  AND project_id = $2
`

type GetProjectDocParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	ProjectID uuid.UUID `db:"project_id" json:"projectId"`
}

func (q *Queries) GetProjectDoc(ctx context.Context, arg GetProjectDocParams) (ProjectDoc, error) {
	row := q.db.QueryRow(ctx, getProjectDoc, arg.ID, arg.ProjectID)
	var i ProjectDoc
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Title,
		&i.BodyMd,
		&i.CreatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectDocBySlug = `-- name: GetProjectDocBySlug :one
SELECT id, project_id, slug, title, body_md, created_by, updated_at
FROM project_docs
WHERE project_id = $1
  AND slug = $2
`

type GetProjectDocBySlugParams struct {
	ProjectID uuid.UUID `db:"project_id" json:"projectId"`
	Slug      string    `db:"slug" json:"slug"`
}

func (q *Queries) GetProjectDocBySlug(ctx context.Context, arg GetProjectDocBySlugParams) (ProjectDoc, error) {
	row := q.db.QueryRow(ctx, getProjectDocBySlug, arg.ProjectID, arg.Slug)
	var i ProjectDoc
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Title,
		&i.BodyMd,
		&i.CreatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectMemberRole = `-- name: GetProjectMemberRole :one
SELECT role
FROM project_members
WHERE project_id = $1
  AND user_id = $2
`

type GetProjectMemberRoleParams struct {
	ProjectID uuid.UUID `db:"project_id" json:"projectId"`
	UserID    uuid.UUID `db:"user_id" json:"userId"`
}

func (q *Queries) GetProjectMemberRole(ctx context.Context, arg GetProjectMemberRoleParams) (ProjectMemberRole, error) {
	row := q.db.QueryRow(ctx, getProjectMemberRole, arg.ProjectID, arg.UserID)
	var role ProjectMemberRole
	err := row.Scan(&role)
	return role, err
}

const isProjectConversationLinked = `-- name: IsProjectConversationLinked :one
SELECT EXISTS (SELECT 1
               FROM project_conversations
               WHERE project_id = $1
                 AND conversation_id = $2) AS linked
`

type IsProjectConversationLinkedParams struct {
	ProjectID      uuid.UUID `db:"project_id" json:"projectId"`
	ConversationID uuid.UUID `db:"conversation_id" json:"conversationId"`
}

func (q *Queries) IsProjectConversationLinked(ctx context.Context, arg IsProjectConversationLinkedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isProjectConversationLinked, arg.ProjectID, arg.ConversationID)
	var linked bool
	err := row.Scan(&linked)
	return linked, err
}

const isProjectMember = `-- name: IsProjectMember :one
SELECT EXISTS (SELECT 1
               FROM project_members
               WHERE project_id = $1
                 AND user_id = $2) AS is_member
`

type IsProjectMemberParams struct {
	ProjectID uuid.UUID `db:"project_id" json:"projectId"`
	UserID    uuid.UUID `db:"user_id" json:"userId"`
}

func (q *Queries) IsProjectMember(ctx context.Context, arg IsProjectMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isProjectMember, arg.ProjectID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const linkProjectConversation = `-- name: LinkProjectConversation :exec
INSERT INTO project_conversations (project_id, conversation_id, linked_at)
VALUES ($1, $2, $3)
ON CONFLICT (project_id, conversation_id) DO NOTHING
`

type LinkProjectConversationParams struct {
	ProjectID      uuid.UUID          `db:"project_id" json:"projectId"`
	ConversationID uuid.UUID          `db:"conversation_id" json:"conversationId"`
	LinkedAt       pgtype.Timestamptz `db:"linked_at" json:"linkedAt"`
}

func (q *Queries) LinkProjectConversation(ctx context.Context, arg LinkProjectConversationParams) error {
	_, err := q.db.Exec(ctx, linkProjectConversation, arg.ProjectID, arg.ConversationID, arg.LinkedAt)
	return err
}

const listConversationProjects = `-- name: ListConversationProjects :many
SELECT p.id,
       p.name,
       p.description,
       p.created_by,
       p.created_at
FROM project_conversations pc
         JOIN projects p ON p.id = pc.project_id
         JOIN project_members pm ON pm.project_id = p.id AND pm.user_id = $2
WHERE pc.conversation_id = $1
ORDER BY p.name ASC
`

type ListConversationProjectsParams struct {
	ConversationID uuid.UUID `db:"conversation_id" json:"conversationId"`
	UserID         uuid.UUID `db:"user_id" json:"userId"`
}

func (q *Queries) ListConversationProjects(ctx context.Context, arg ListConversationProjectsParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listConversationProjects, arg.ConversationID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectConversations = `-- name: ListProjectConversations :many
SELECT pc.project_id,
       pc.conversation_id,
       pc.linked_at,
       c.type,
       c.title,
       c.slug
FROM project_conversations pc
         JOIN conversations c ON c.id = pc.conversation_id
WHERE pc.project_id = $1
ORDER BY pc.linked_at DESC
`

type ListProjectConversationsRow struct {
	ProjectID      uuid.UUID          `db:"project_id" json:"projectId"`
	ConversationID uuid.UUID          `db:"conversation_id" json:"conversationId"`
	LinkedAt       pgtype.Timestamptz `db:"linked_at" json:"linkedAt"`
	Type           ConversationType   `db:"type" json:"type"`
	Title          pgtype.Text        `db:"title" json:"title"`
	Slug           pgtype.Text        `db:"slug" json:"slug"`
}

func (q *Queries) ListProjectConversations(ctx context.Context, projectID uuid.UUID) ([]ListProjectConversationsRow, error) {
	rows, err := q.db.Query(ctx, listProjectConversations, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectConversationsRow{}
	for rows.Next() {
		var i ListProjectConversationsRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.ConversationID,
			&i.LinkedAt,
			&i.Type,
			&i.Title,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectDecisions = `-- name: ListProjectDecisions :many
SELECT id, project_id, summary, context, status, message_id, created_by, created_at
FROM project_decisions
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListProjectDecisions(ctx context.Context, projectID uuid.UUID) ([]ProjectDecision, error) {
	rows, err := q.db.Query(ctx, listProjectDecisions, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectDecision{}
	for rows.Next() {
		var i ProjectDecision
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Summary,
			&i.Context,
			&i.Status,
			&i.MessageID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectDocs = `-- name: ListProjectDocs :many
SELECT id, project_id, slug, title, created_by, updated_at
FROM project_docs
WHERE project_id = $1
ORDER BY updated_at DESC
`

type ListProjectDocsRow struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	ProjectID uuid.UUID          `db:"project_id" json:"projectId"`
	Slug      string             `db:"slug" json:"slug"`
	Title     string             `db:"title" json:"title"`
	CreatedBy uuid.UUID          `db:"created_by" json:"createdBy"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

func (q *Queries) ListProjectDocs(ctx context.Context, projectID uuid.UUID) ([]ListProjectDocsRow, error) {
	rows, err := q.db.Query(ctx, listProjectDocs, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectDocsRow{}
	for rows.Next() {
		var i ListProjectDocsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Slug,
			&i.Title,
			&i.CreatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT pm.project_id,
       pm.user_id,
       pm.role,
       pm.joined_at,
       u.username,
       u.avatar_url
FROM project_members pm
         JOIN users u ON u.id = pm.user_id
WHERE pm.project_id = $1
ORDER BY pm.joined_at ASC
`

type ListProjectMembersRow struct {
	ProjectID uuid.UUID          `db:"project_id" json:"projectId"`
	UserID    uuid.UUID          `db:"user_id" json:"userId"`
	Role      ProjectMemberRole  `db:"role" json:"role"`
	JoinedAt  pgtype.Timestamptz `db:"joined_at" json:"joinedAt"`
	Username  pgtype.Text        `db:"username" json:"username"`
	AvatarUrl pgtype.Text        `db:"avatar_url" json:"avatarUrl"`
}

func (q *Queries) ListProjectMembers(ctx context.Context, projectID uuid.UUID) ([]ListProjectMembersRow, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectMembersRow{}
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.Username,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserProjects = `-- name: ListUserProjects :many
SELECT p.id,
       p.name,
       p.description,
       p.created_by,
       p.created_at,
       (SELECT COUNT(*)::INT FROM project_members pm WHERE pm.project_id = p.id) AS member_count,
       (SELECT COUNT(*)::INT FROM project_docs pd WHERE pd.project_id = p.id)    AS doc_count
FROM projects p
         JOIN project_members pm ON pm.project_id = p.id AND pm.user_id = $1
ORDER BY p.created_at DESC
`

type ListUserProjectsRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	Description string             `db:"description" json:"description"`
	CreatedBy   uuid.UUID          `db:"created_by" json:"createdBy"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	MemberCount int32              `db:"member_count" json:"memberCount"`
	DocCount    int32              `db:"doc_count" json:"docCount"`
}

func (q *Queries) ListUserProjects(ctx context.Context, userID uuid.UUID) ([]ListUserProjectsRow, error) {
	rows, err := q.db.Query(ctx, listUserProjects, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserProjectsRow{}
	for rows.Next() {
		var i ListUserProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.MemberCount,
			&i.DocCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectDocSlugExists = `-- name: ProjectDocSlugExists :one
SELECT EXISTS (SELECT 1
               FROM project_docs
               WHERE project_id = $1
                 AND slug = $2) AS exists
`

type ProjectDocSlugExistsParams struct {
	ProjectID uuid.UUID `db:"project_id" json:"projectId"`
	Slug      string    `db:"slug" json:"slug"`
}

func (q *Queries) ProjectDocSlugExists(ctx context.Context, arg ProjectDocSlugExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, projectDocSlugExists, arg.ProjectID, arg.Slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const unlinkProjectConversation = `-- name: UnlinkProjectConversation :exec
DELETE
FROM project_conversations
WHERE project_id = $1
  AND conversation_id = $2
`

type UnlinkProjectConversationParams struct {
	ProjectID      uuid.UUID `db:"project_id" json:"projectId"`
	ConversationID uuid.UUID `db:"conversation_id" json:"conversationId"`
}

func (q *Queries) UnlinkProjectConversation(ctx context.Context, arg UnlinkProjectConversationParams) error {
	_, err := q.db.Exec(ctx, unlinkProjectConversation, arg.ProjectID, arg.ConversationID)
	return err
}

const updateProjectDecisionStatus = `-- name: UpdateProjectDecisionStatus :one
UPDATE project_decisions
SET status = $3
WHERE id = $1
  AND project_id = $2
RETURNING id, project_id, summary, context, status, message_id, created_by, created_at
`

type UpdateProjectDecisionStatusParams struct {
	ID        uuid.UUID      `db:"id" json:"id"`
	ProjectID uuid.UUID      `db:"project_id" json:"projectId"`
	Status    DecisionStatus `db:"status" json:"status"`
}

func (q *Queries) UpdateProjectDecisionStatus(ctx context.Context, arg UpdateProjectDecisionStatusParams) (ProjectDecision, error) {
	row := q.db.QueryRow(ctx, updateProjectDecisionStatus, arg.ID, arg.ProjectID, arg.Status)
	var i ProjectDecision
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Summary,
		&i.Context,
		&i.Status,
		&i.MessageID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const updateProjectDoc = `-- name: UpdateProjectDoc :one
UPDATE project_docs
SET title    = $3,
    body_md  = $4,
    updated_at = $5
WHERE id = $1
  AND project_id = $2
RETURNING id, project_id, slug, title, body_md, created_by, updated_at
`

type UpdateProjectDocParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	ProjectID uuid.UUID          `db:"project_id" json:"projectId"`
	Title     string             `db:"title" json:"title"`
	BodyMd    string             `db:"body_md" json:"bodyMd"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

func (q *Queries) UpdateProjectDoc(ctx context.Context, arg UpdateProjectDocParams) (ProjectDoc, error) {
	row := q.db.QueryRow(ctx, updateProjectDoc,
		arg.ID,
		arg.ProjectID,
		arg.Title,
		arg.BodyMd,
		arg.UpdatedAt,
	)
	var i ProjectDoc
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Title,
		&i.BodyMd,
		&i.CreatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
