// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddConversationMember(ctx context.Context, arg AddConversationMemberParams) error
	ClearUserPassword(ctx context.Context, id uuid.UUID) error
	ConversationExists(ctx context.Context, id uuid.UUID) (bool, error)
	CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error)
	CreateDMPair(ctx context.Context, arg CreateDMPairParams) error
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePhoneOTP(ctx context.Context, phone string) error
	FindDMConversation(ctx context.Context, arg FindDMConversationParams) (uuid.UUID, error)
	GetConversation(ctx context.Context, id uuid.UUID) (Conversation, error)
	GetConversationBySlug(ctx context.Context, slug pgtype.Text) (Conversation, error)
	GetMessagesPaging(ctx context.Context, arg GetMessagesPagingParams) ([]GetMessagesPagingRow, error)
	GetPhoneOTP(ctx context.Context, phone string) (PhoneOtpCode, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	GetUserByUsername(ctx context.Context, username pgtype.Text) (User, error)
	GetUserConversations(ctx context.Context, userID uuid.UUID) ([]Conversation, error)
	IncrementPhoneOTPAttempts(ctx context.Context, phone string) error
	IsConversationMember(ctx context.Context, arg IsConversationMemberParams) (bool, error)
	SetUsername(ctx context.Context, arg SetUsernameParams) error
	UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpsertPhoneOTP(ctx context.Context, arg UpsertPhoneOTPParams) error
	UserWithPhoneExists(ctx context.Context, phone string) (bool, error)
	UserWithUsernameExists(ctx context.Context, username pgtype.Text) (bool, error)
}

var _ Querier = (*Queries)(nil)
