// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddConversationMember(ctx context.Context, arg AddConversationMemberParams) error
	AddMessageReaction(ctx context.Context, arg AddMessageReactionParams) error
	AddProjectMember(ctx context.Context, arg AddProjectMemberParams) error
	AdvanceMemberLastReadAt(ctx context.Context, arg AdvanceMemberLastReadAtParams) (pgtype.Timestamptz, error)
	AttachToMessage(ctx context.Context, arg AttachToMessageParams) error
	ClearUserPassword(ctx context.Context, id uuid.UUID) error
	ConversationExists(ctx context.Context, id uuid.UUID) (bool, error)
	CountPendingAttachments(ctx context.Context, arg CountPendingAttachmentsParams) (int64, error)
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (MessageAttachment, error)
	CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error)
	CreateDMPair(ctx context.Context, arg CreateDMPairParams) error
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateProjectDecision(ctx context.Context, arg CreateProjectDecisionParams) (ProjectDecision, error)
	CreateProjectDoc(ctx context.Context, arg CreateProjectDocParams) (ProjectDoc, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteMessageForEveryone(ctx context.Context, arg DeleteMessageForEveryoneParams) (Message, error)
	DeletePhoneOTP(ctx context.Context, phone string) error
	DeleteProjectDoc(ctx context.Context, arg DeleteProjectDocParams) error
	FindDMConversation(ctx context.Context, arg FindDMConversationParams) (uuid.UUID, error)
	GetAttachmentByID(ctx context.Context, id uuid.UUID) (MessageAttachment, error)
	GetConversation(ctx context.Context, id uuid.UUID) (Conversation, error)
	GetConversationBySlug(ctx context.Context, slug pgtype.Text) (Conversation, error)
	GetMemberLastReadAt(ctx context.Context, arg GetMemberLastReadAtParams) (pgtype.Timestamptz, error)
	GetMessageByID(ctx context.Context, id uuid.UUID) (GetMessageByIDRow, error)
	GetMessageReactionUsers(ctx context.Context, messageID uuid.UUID) ([]GetMessageReactionUsersRow, error)
	GetMessageReactions(ctx context.Context, arg GetMessageReactionsParams) ([]GetMessageReactionsRow, error)
	GetMessagesPaging(ctx context.Context, arg GetMessagesPagingParams) ([]GetMessagesPagingRow, error)
	GetOthersReadWatermark(ctx context.Context, arg GetOthersReadWatermarkParams) (pgtype.Timestamptz, error)
	GetPhoneOTP(ctx context.Context, phone string) (PhoneOtpCode, error)
	GetProject(ctx context.Context, id uuid.UUID) (Project, error)
	GetProjectDecision(ctx context.Context, arg GetProjectDecisionParams) (ProjectDecision, error)
	GetProjectDoc(ctx context.Context, arg GetProjectDocParams) (ProjectDoc, error)
	GetProjectDocBySlug(ctx context.Context, arg GetProjectDocBySlugParams) (ProjectDoc, error)
	GetProjectMemberRole(ctx context.Context, arg GetProjectMemberRoleParams) (ProjectMemberRole, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	GetUserByUsername(ctx context.Context, lower string) (User, error)
	GetUserConversations(ctx context.Context, senderID uuid.UUID) ([]GetUserConversationsRow, error)
	HideMessageForUser(ctx context.Context, arg HideMessageForUserParams) error
	IncrementPhoneOTPAttempts(ctx context.Context, phone string) error
	IsConversationMember(ctx context.Context, arg IsConversationMemberParams) (bool, error)
	IsProjectConversationLinked(ctx context.Context, arg IsProjectConversationLinkedParams) (bool, error)
	IsProjectMember(ctx context.Context, arg IsProjectMemberParams) (bool, error)
	LinkProjectConversation(ctx context.Context, arg LinkProjectConversationParams) error
	ListAttachmentsByMessageIDs(ctx context.Context, messageIds []uuid.UUID) ([]MessageAttachment, error)
	ListConversationMedia(ctx context.Context, arg ListConversationMediaParams) ([]MessageAttachment, error)
	ListConversationMemberIDs(ctx context.Context, conversationID uuid.UUID) ([]uuid.UUID, error)
	ListConversationProjects(ctx context.Context, arg ListConversationProjectsParams) ([]Project, error)
	ListProjectConversations(ctx context.Context, projectID uuid.UUID) ([]ListProjectConversationsRow, error)
	ListProjectDecisions(ctx context.Context, projectID uuid.UUID) ([]ProjectDecision, error)
	ListProjectDocs(ctx context.Context, projectID uuid.UUID) ([]ListProjectDocsRow, error)
	ListProjectMembers(ctx context.Context, projectID uuid.UUID) ([]ListProjectMembersRow, error)
	ListUserProjects(ctx context.Context, userID uuid.UUID) ([]ListUserProjectsRow, error)
	ProjectDocSlugExists(ctx context.Context, arg ProjectDocSlugExistsParams) (bool, error)
	RemoveConversationMember(ctx context.Context, arg RemoveConversationMemberParams) error
	RemoveMessageReaction(ctx context.Context, arg RemoveMessageReactionParams) error
	SearchUsersByUsernamePrefix(ctx context.Context, arg SearchUsersByUsernamePrefixParams) ([]SearchUsersByUsernamePrefixRow, error)
	SetUsername(ctx context.Context, arg SetUsernameParams) error
	UnlinkProjectConversation(ctx context.Context, arg UnlinkProjectConversationParams) error
	UpdateProjectDecisionStatus(ctx context.Context, arg UpdateProjectDecisionStatusParams) (ProjectDecision, error)
	UpdateProjectDoc(ctx context.Context, arg UpdateProjectDocParams) (ProjectDoc, error)
	UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserPrivacy(ctx context.Context, arg UpdateUserPrivacyParams) error
	UpdateUsername(ctx context.Context, arg UpdateUsernameParams) error
	UpsertPhoneOTP(ctx context.Context, arg UpsertPhoneOTPParams) error
	UserWithPhoneExists(ctx context.Context, phone string) (bool, error)
	UserWithUsernameExists(ctx context.Context, lower string) (bool, error)
}

var _ Querier = (*Queries)(nil)
