// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddConversationMember(ctx context.Context, arg AddConversationMemberParams) error
	ConversationExists(ctx context.Context, id uuid.UUID) (bool, error)
	CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error)
	CreateDMPair(ctx context.Context, arg CreateDMPairParams) error
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteEmailVerificationCode(ctx context.Context, userID uuid.UUID) error
	FindDMConversation(ctx context.Context, arg FindDMConversationParams) (uuid.UUID, error)
	GetConversation(ctx context.Context, id uuid.UUID) (Conversation, error)
	GetConversationBySlug(ctx context.Context, slug pgtype.Text) (Conversation, error)
	GetEmailVerificationCode(ctx context.Context, userID uuid.UUID) (EmailVerificationCode, error)
	GetEmailVerificationCodeByEmail(ctx context.Context, pendingEmail pgtype.Text) (EmailVerificationCode, error)
	GetMessagesPaging(ctx context.Context, arg GetMessagesPagingParams) ([]GetMessagesPagingRow, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByLogin(ctx context.Context, login string) (User, error)
	GetUserConversations(ctx context.Context, userID uuid.UUID) ([]Conversation, error)
	IncrementVerificationAttempts(ctx context.Context, userID uuid.UUID) error
	IsConversationMember(ctx context.Context, arg IsConversationMemberParams) (bool, error)
	MarkEmailVerified(ctx context.Context, id uuid.UUID) error
	UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpsertEmailVerificationCode(ctx context.Context, arg UpsertEmailVerificationCodeParams) error
	UserWithEmailExists(ctx context.Context, email string) (bool, error)
	UserWithUsernameExists(ctx context.Context, username string) (bool, error)
}

var _ Querier = (*Queries)(nil)
