// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, email, password_hash, created_at, avatar_url, email_verified)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, username, email, email_verified, password_hash, created_at, avatar_url
`

type CreateUserParams struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	Username      string             `db:"username" json:"username"`
	Email         string             `db:"email" json:"email"`
	PasswordHash  pgtype.Text        `db:"password_hash" json:"passwordHash"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	AvatarUrl     pgtype.Text        `db:"avatar_url" json:"avatarUrl"`
	EmailVerified bool               `db:"email_verified" json:"emailVerified"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.AvatarUrl,
		arg.EmailVerified,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.AvatarUrl,
	)
	return i, err
}

const deleteEmailVerificationCode = `-- name: DeleteEmailVerificationCode :exec
DELETE FROM email_verification_codes
WHERE user_id = $1
`

func (q *Queries) DeleteEmailVerificationCode(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmailVerificationCode, userID)
	return err
}

const getEmailVerificationCode = `-- name: GetEmailVerificationCode :one
SELECT user_id, code_hash, expires_at, attempts, created_at, pending_email
FROM email_verification_codes
WHERE user_id = $1
`

func (q *Queries) GetEmailVerificationCode(ctx context.Context, userID uuid.UUID) (EmailVerificationCode, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationCode, userID)
	var i EmailVerificationCode
	err := row.Scan(
		&i.UserID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.CreatedAt,
		&i.PendingEmail,
	)
	return i, err
}

const getEmailVerificationCodeByEmail = `-- name: GetEmailVerificationCodeByEmail :one
SELECT user_id, code_hash, expires_at, attempts, created_at, pending_email
FROM email_verification_codes
WHERE pending_email = $1
`

func (q *Queries) GetEmailVerificationCodeByEmail(ctx context.Context, pendingEmail pgtype.Text) (EmailVerificationCode, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationCodeByEmail, pendingEmail)
	var i EmailVerificationCode
	err := row.Scan(
		&i.UserID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.CreatedAt,
		&i.PendingEmail,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, email, email_verified, password_hash, created_at, avatar_url
FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.AvatarUrl,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT id, username, email, email_verified, password_hash, created_at, avatar_url
FROM users
WHERE username = $1
   OR email = $1 LIMIT 1
`

func (q *Queries) GetUserByLogin(ctx context.Context, login string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByLogin, login)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.AvatarUrl,
	)
	return i, err
}

const incrementVerificationAttempts = `-- name: IncrementVerificationAttempts :exec
UPDATE email_verification_codes
SET attempts = attempts + 1
WHERE user_id = $1
`

func (q *Queries) IncrementVerificationAttempts(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementVerificationAttempts, userID)
	return err
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE users
SET email_verified = true
WHERE id = $1
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEmailVerified, id)
	return err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :exec
UPDATE users
SET avatar_url = $1
WHERE id = $2
`

type UpdateUserAvatarParams struct {
	AvatarUrl pgtype.Text `db:"avatar_url" json:"avatarUrl"`
	ID        uuid.UUID   `db:"id" json:"id"`
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error {
	_, err := q.db.Exec(ctx, updateUserAvatar, arg.AvatarUrl, arg.ID)
	return err
}

const updateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE users
SET email = $1
WHERE id = $2
`

type UpdateUserEmailParams struct {
	Email string    `db:"email" json:"email"`
	ID    uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.Exec(ctx, updateUserEmail, arg.Email, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $1
WHERE id = $2
`

type UpdateUserPasswordParams struct {
	PasswordHash pgtype.Text `db:"password_hash" json:"passwordHash"`
	ID           uuid.UUID   `db:"id" json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const upsertEmailVerificationCode = `-- name: UpsertEmailVerificationCode :exec
INSERT INTO email_verification_codes (user_id, code_hash, pending_email, expires_at, attempts, created_at)
VALUES ($1, $2, $3, $4, $5, $6) ON CONFLICT (user_id) DO
UPDATE
    SET code_hash = EXCLUDED.code_hash,
    pending_email = EXCLUDED.pending_email,
    expires_at = EXCLUDED.expires_at,
    attempts = EXCLUDED.attempts,
    created_at = EXCLUDED.created_at
`

type UpsertEmailVerificationCodeParams struct {
	UserID       uuid.UUID          `db:"user_id" json:"userId"`
	CodeHash     string             `db:"code_hash" json:"codeHash"`
	PendingEmail pgtype.Text        `db:"pending_email" json:"pendingEmail"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at" json:"expiresAt"`
	Attempts     int32              `db:"attempts" json:"attempts"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

func (q *Queries) UpsertEmailVerificationCode(ctx context.Context, arg UpsertEmailVerificationCodeParams) error {
	_, err := q.db.Exec(ctx, upsertEmailVerificationCode,
		arg.UserID,
		arg.CodeHash,
		arg.PendingEmail,
		arg.ExpiresAt,
		arg.Attempts,
		arg.CreatedAt,
	)
	return err
}

const userWithEmailExists = `-- name: UserWithEmailExists :one
SELECT EXISTS (SELECT 1
               FROM users
               WHERE email = $1)
`

func (q *Queries) UserWithEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, userWithEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userWithUsernameExists = `-- name: UserWithUsernameExists :one
SELECT EXISTS (SELECT 1
               FROM users
               WHERE username = $1)
`

func (q *Queries) UserWithUsernameExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, userWithUsernameExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
