// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearUserPassword = `-- name: ClearUserPassword :exec
UPDATE users
SET password_hash = NULL
WHERE id = $1
`

func (q *Queries) ClearUserPassword(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearUserPassword, id)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, phone, created_at)
VALUES ($1, $2, $3)
RETURNING id, phone, username, password_hash, avatar_url, created_at, username_searchable, dm_policy
`

type CreateUserParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Phone     string             `db:"phone" json:"phone"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.Phone, arg.CreatedAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Username,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UsernameSearchable,
		&i.DmPolicy,
	)
	return i, err
}

const deletePhoneOTP = `-- name: DeletePhoneOTP :exec
DELETE
FROM phone_otp_codes
WHERE phone = $1
`

func (q *Queries) DeletePhoneOTP(ctx context.Context, phone string) error {
	_, err := q.db.Exec(ctx, deletePhoneOTP, phone)
	return err
}

const getPhoneOTP = `-- name: GetPhoneOTP :one
SELECT phone, code_hash, expires_at, attempts, sent_at, created_at
FROM phone_otp_codes
WHERE phone = $1
`

func (q *Queries) GetPhoneOTP(ctx context.Context, phone string) (PhoneOtpCode, error) {
	row := q.db.QueryRow(ctx, getPhoneOTP, phone)
	var i PhoneOtpCode
	err := row.Scan(
		&i.Phone,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, phone, username, password_hash, avatar_url, created_at, username_searchable, dm_policy
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Username,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UsernameSearchable,
		&i.DmPolicy,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, phone, username, password_hash, avatar_url, created_at, username_searchable, dm_policy
FROM users
WHERE phone = $1
LIMIT 1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Username,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UsernameSearchable,
		&i.DmPolicy,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, phone, username, password_hash, avatar_url, created_at, username_searchable, dm_policy
FROM users
WHERE lower(username) = lower($1)
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Username,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UsernameSearchable,
		&i.DmPolicy,
	)
	return i, err
}

const incrementPhoneOTPAttempts = `-- name: IncrementPhoneOTPAttempts :exec
UPDATE phone_otp_codes
SET attempts = attempts + 1
WHERE phone = $1
`

func (q *Queries) IncrementPhoneOTPAttempts(ctx context.Context, phone string) error {
	_, err := q.db.Exec(ctx, incrementPhoneOTPAttempts, phone)
	return err
}

const searchUsersByUsernamePrefix = `-- name: SearchUsersByUsernamePrefix :many
SELECT id, username, avatar_url
FROM users
WHERE username IS NOT NULL
  AND username_searchable = true
  AND lower(username) LIKE lower($1) || '%'
  AND id <> $2
ORDER BY username
LIMIT $3
`

type SearchUsersByUsernamePrefixParams struct {
	Prefix        string    `db:"prefix" json:"prefix"`
	ExcludeUserID uuid.UUID `db:"exclude_user_id" json:"excludeUserId"`
	ResultLimit   int32     `db:"result_limit" json:"resultLimit"`
}

type SearchUsersByUsernamePrefixRow struct {
	ID        uuid.UUID   `db:"id" json:"id"`
	Username  pgtype.Text `db:"username" json:"username"`
	AvatarUrl pgtype.Text `db:"avatar_url" json:"avatarUrl"`
}

func (q *Queries) SearchUsersByUsernamePrefix(ctx context.Context, arg SearchUsersByUsernamePrefixParams) ([]SearchUsersByUsernamePrefixRow, error) {
	rows, err := q.db.Query(ctx, searchUsersByUsernamePrefix, arg.Prefix, arg.ExcludeUserID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersByUsernamePrefixRow{}
	for rows.Next() {
		var i SearchUsersByUsernamePrefixRow
		if err := rows.Scan(&i.ID, &i.Username, &i.AvatarUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUsername = `-- name: SetUsername :exec
UPDATE users
SET username = $1
WHERE id = $2
`

type SetUsernameParams struct {
	Username pgtype.Text `db:"username" json:"username"`
	ID       uuid.UUID   `db:"id" json:"id"`
}

func (q *Queries) SetUsername(ctx context.Context, arg SetUsernameParams) error {
	_, err := q.db.Exec(ctx, setUsername, arg.Username, arg.ID)
	return err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :exec
UPDATE users
SET avatar_url = $1
WHERE id = $2
`

type UpdateUserAvatarParams struct {
	AvatarUrl pgtype.Text `db:"avatar_url" json:"avatarUrl"`
	ID        uuid.UUID   `db:"id" json:"id"`
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error {
	_, err := q.db.Exec(ctx, updateUserAvatar, arg.AvatarUrl, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $1
WHERE id = $2
`

type UpdateUserPasswordParams struct {
	PasswordHash pgtype.Text `db:"password_hash" json:"passwordHash"`
	ID           uuid.UUID   `db:"id" json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const updateUserPrivacy = `-- name: UpdateUserPrivacy :exec
UPDATE users
SET username_searchable = $1,
    dm_policy           = $2
WHERE id = $3
`

type UpdateUserPrivacyParams struct {
	UsernameSearchable bool      `db:"username_searchable" json:"usernameSearchable"`
	DmPolicy           string    `db:"dm_policy" json:"dmPolicy"`
	ID                 uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateUserPrivacy(ctx context.Context, arg UpdateUserPrivacyParams) error {
	_, err := q.db.Exec(ctx, updateUserPrivacy, arg.UsernameSearchable, arg.DmPolicy, arg.ID)
	return err
}

const updateUsername = `-- name: UpdateUsername :exec
UPDATE users
SET username = $1
WHERE id = $2
`

type UpdateUsernameParams struct {
	Username pgtype.Text `db:"username" json:"username"`
	ID       uuid.UUID   `db:"id" json:"id"`
}

func (q *Queries) UpdateUsername(ctx context.Context, arg UpdateUsernameParams) error {
	_, err := q.db.Exec(ctx, updateUsername, arg.Username, arg.ID)
	return err
}

const upsertPhoneOTP = `-- name: UpsertPhoneOTP :exec
INSERT INTO phone_otp_codes (phone, code_hash, expires_at, attempts, sent_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (phone) DO UPDATE
    SET code_hash  = EXCLUDED.code_hash,
        expires_at = EXCLUDED.expires_at,
        attempts   = EXCLUDED.attempts,
        sent_at    = EXCLUDED.sent_at,
        created_at = EXCLUDED.created_at
`

type UpsertPhoneOTPParams struct {
	Phone     string             `db:"phone" json:"phone"`
	CodeHash  string             `db:"code_hash" json:"codeHash"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expiresAt"`
	Attempts  int32              `db:"attempts" json:"attempts"`
	SentAt    pgtype.Timestamptz `db:"sent_at" json:"sentAt"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

func (q *Queries) UpsertPhoneOTP(ctx context.Context, arg UpsertPhoneOTPParams) error {
	_, err := q.db.Exec(ctx, upsertPhoneOTP,
		arg.Phone,
		arg.CodeHash,
		arg.ExpiresAt,
		arg.Attempts,
		arg.SentAt,
		arg.CreatedAt,
	)
	return err
}

const userWithPhoneExists = `-- name: UserWithPhoneExists :one
SELECT EXISTS (SELECT 1
               FROM users
               WHERE phone = $1)
`

func (q *Queries) UserWithPhoneExists(ctx context.Context, phone string) (bool, error) {
	row := q.db.QueryRow(ctx, userWithPhoneExists, phone)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userWithUsernameExists = `-- name: UserWithUsernameExists :one
SELECT EXISTS (SELECT 1
               FROM users
               WHERE lower(username) = lower($1))
`

func (q *Queries) UserWithUsernameExists(ctx context.Context, lower string) (bool, error) {
	row := q.db.QueryRow(ctx, userWithUsernameExists, lower)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
